version: "3.7"

services:
  db:
    image: "postgres:13-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    image: "finanzer:0.0.39"
    environment:
      NODE_ENV: "production"
      PORT: "3000"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/finanzer_production?schema=public"
    ports:
      - 3000:3000
    depends_on:
      - db
