version: "3.7"

services:
  db:
    image: "postgres:13-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "db:/var/lib/postgresql/data"
  app:
    stdin_open: true
    tty: true
    build:
      context: .
      target: ci
    env_file:
      - .env.sample
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  db:
