name: ci

on:
  pull_request:

jobs:
  deploy:
    name: ci
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v2
      - name: Run tests
        id: run-tests
        run: make prod_spec
