name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v2
      - name: Push to Docker Repository
        id: build-and-deploy
        run: make prod_deploy
        env:
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
          DOCKER_REPO_USERNAME: ${{ secrets.DOCKER_REPO_USERNAME }}
          DOCKER_REPO_PASSWORD: ${{ secrets.DOCKER_REPO_PASSWORD }}
      - name: Start service with new image
        id: start-service
        run: make start_service
        env:
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
          DOCKER_REPO_USERNAME: ${{ secrets.DOCKER_REPO_USERNAME }}
          DOCKER_REPO_PASSWORD: ${{ secrets.DOCKER_REPO_PASSWORD }}
          DEPLOY_AUTH: ${{ secrets.DEPLOY_AUTH }}
          DEPLOY_ACTION_URL: ${{ secrets.DEPLOY_ACTION_URL }}
